### ISSUE TITLE
Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by moorthi07** [kechol/grunt-dpdjs#1]
Hi ,
Looking to package dpd.js into dist, instead dynamically loading it. I get this error, when I run the grunt file.
Any idea, why?

Running "dpdjs" task

Error loading module node_modules/dpd-fileupload
TypeError: Cannot read property 'options' of undefined
    at Object.<anonymous> (c:\Users.....\node_modules\dpd-fileupload\index.js:13:32)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at c:\Users........\node_modules\deployd\lib\type-loader.js:25:32
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)

**Comment by moorthi07** [comment]
The issue is the dpd-fileupload expects a 'process.server' object. Here is the issue opened in dpd-fileupload issues.

 https://github.com/NicolasRitouet/dpd-fileupload/issues/72
